SetFactory("OpenCASCADE");
Merge "block.brep";
Mesh.MeshSizeMin=1.35;
Mesh.MeshSizeMax=5;
Mesh.MeshSizeFromCurvature=14;
Mesh.ElementOrder=2;
Mesh.SecondOrderLinear=1;
Mesh.Optimize=1;
Mesh.SaveAll=1;
Mesh.MshFileVersion=2.2;
