SetFactory("OpenCASCADE");
Merge "block.brep";
Mesh.CharacteristicLengthMin = 1.5;
Mesh.CharacteristicLengthMax = 6;
Mesh.MeshSizeFromCurvature = 12;
Mesh.ElementOrder = 2;
Mesh.SecondOrderLinear = 1;
Mesh.Optimize = 1;
Mesh.SaveAll = 1;
Mesh.MshFileVersion = 2.2;
